# Generated by Django 3.2.7 on 2021-10-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
